### ISSUE TITLE
Upgrade the project meta data to support new catalog commands

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-pageview-map#23]
Add metadata to the repository that matches the example laid out here.
- [x] Add a `config.json` file to a `catalog` directory in the repo root, [matching this format](https://github.com/newrelic/nr1-catalog/blob/master/examples/catalog/config.json).
- [ ] Add a `documentation.md` file to a `catalog` directory in the repo root, [matching this format](https://github.com/newrelic/nr1-catalog/blob/master/examples/catalog/documentation.md).
- [x] (Optional) If there's additional documentation referenced in the repo, add a `additionalInfo.md` file to a `catalog` directory in the repo root, [matching this format](https://github.com/newrelic/nr1-catalog/blob/master/examples/catalog/additionalInfo.md).
- [ ] Add one or more `screenshots` to a `catalog/screenshots` directory in the repo root, [matching this format](https://github.com/newrelic/nr1-catalog/tree/master/examples/catalog/screenshots).
